### ISSUE TITLE
PhpEpsolarTracer and MT50 at the same time?

### ISSUE THREAD

**Issue by spmp** [toggio/PhpEpsolarTracer#11]
Good day,
 Does anyone know if I can have the MT50 and the RS485 to USB adaptor with phpEpsolarTracer connected at the same time and working 8)

Cheers

**Comment by acmorfe** [comment]
i think that is possible... if it doesn't work, maybe it is due to the polling interval of the mt50. 
i don't have an mt50 but i will try it tonight with the usb cable and my wifi to rs485 bridge hub.

**Comment by spmp** [comment]
Cheers, awaiting results 8)

**Comment by spmp** [comment]
Cheers, awaiting results 8)

**Comment by acmorfe** [comment]
it works! :) 
--(#1) PC wired to network
--(#2) laptop with usb-to-rs485 cable plugged into the hub(#3)
--(#3) DIY 3-port wifi to rs485 hub wired to 2 epever tracer 4210a, wifi connected to the network
both #1 and #2 are running 2 instances each of the epever solar station monitor software with read intervals of 30 seconds -- "simultaneously" reading data from the charge controllers.

**Comment by spmp** [comment]
@acmorfe, I am worried that the DIY WiFi hub is acting as a single master and handling client requests... In the case of the MT50 and usb-to-rs485 they are both acting as masters... Anyway, I have no idea about modbus , I just think this test may not prove the point in my situation. Do you think the DIY hub could be modified to have another rs485 connection to plug the MT50 into?
Thanks for testing 8)

**Comment by acmorfe** [comment]
@spmp, no, the diy wifi hub is NOT acting as a single master.

**Comment by spmp** [comment]
Cool! SO all i need to find is an RS485 hub and I'm away. Thanks for testing 8)

**Comment by acmorfe** [comment]
I don't think there is an available rs485 hub out there -- you have to diy one. it's very simple. 
here is the hub I made:
https://www.facebook.com/groups/solarpowerphilippines/permalink/1465782050168690/
just remove all the modules (rs485, ams, esp8266) if you don't want the wifi -- what remains is basically a COM port splitter. :)

addendum: you have to modify the pcb a bit for mt50... the port where you will plug in the mt50 needs VCC (pin 1/2).

**Comment by merald** [comment]
I bought it for building a 1wire network, but I'm pretty sure it's
basically same thing. RJ45 ports that is in parallell.

https://www.unipi.technology/1wire-hub-2-port-p50

Is available as many ports as well, think I have with 5 ports at home.
Can't find the link at the moment.

**Comment by spmp** [comment]
THank you both very much. I will try ASAP!
 @acmorfe  nice work, does it have a github existence?

**Comment by acmorfe** [comment]
@spmp, what is a "github existence"? I am new to github -- less than a month old :(

**Comment by spmp** [comment]
Probably bad spelling 8)
 Do you have a github project for the post on FaceBook, with Readme's with
pictures etc. and artwork, code, etc. etc. 8)

**Comment by spmp** [comment]
Thank you all. That is a confirmed great big YES on both together 8)
 Using a cheap adaptor ( http://www.globalpc.co.nz/Electronics/Connectors/Telephone-Accessories/Product-Specification-P7053.aspx )
Yes!

**Comment by acmorfe** [comment]
@spmp, issue closed?

**Comment by spmp** [comment]
AD hoc queries with MT50 and PhpEpsolarTracer via Exar RS485 to USB converter are successful. I have not tried it with a more frequent polling interval ,  so the success may be accidental.
But for al intents and purposes this should be done.

**Comment by joeyh** [comment]
What happens if the MT50 sends data at the same time that the USB connection is sending data?

Perhaps the USB connection could snoop on the charge controller's responses to the MT50, to passively gather the same data and/or to time any other requests it makes to times then the MT50 is idle.

**Comment by spmp** [comment]
Sounds like an excellent idea!!
 I had worried about this but in practice it has not been an issue. A
caveat to this is that I have not got PhpEpsolarTracer doing its thing
periodically yet... Waiting for time to set up a dashboard...

Any idea how we could passively snoop?

**Comment by wrybread** [comment]
Can anyone confirm that this works longterm? In other words, reading from the Tracer from both a script and the MT50 simultaneously, over a period of time?

**Comment by spmp** [comment]
I will be able to tell you in a week or two. If the correct driver for my
Exar RS485 driver are loaded then all good, but if the wrong kernel module
is present then the MT50 immediately disconnects.
 But so far for the incidental use its been fine 8)

**Comment by wrybread** [comment]
Interesting. I have the Exar cable but haven't been able to get the driver working with my Raspberry Pi. What hardware and OS version are you using?

I made a cable using the instructions here:

https://youtu.be/r3LrWeYYtnQ?t=3m11s

And this to make the cable:

https://www.amazon.com/gp/product/B00NKAJGZM/

Note that I had to ground the cable (pin 7 or 8) to the Pi (any of the ground GPIO pins) or it would lose it's connection whenever the controller went into float.

Grounding the cable greatly improved things, but I'm still losing connection. Connecting the MT50 box for even a moment fixes things (the controller responds again), so I'm wondering if connecting the MT50 and my Pi simultaneously will fix things longterm.

Of course I'd rather figure out why I'm losing connection, and why connecting the MT50 fixes it, if anyone has any ideas there.

**Comment by spmp** [comment]
You need this:
https://github.com/kasbert/epsolar-tracer/tree/master/xr_usb_serial_common-1a
Just had my update to documentation merged 8)
So yea, have the Exar RS485 converter, ubuntu 16.04 on amd65 (i5)

**Comment by wrybread** [comment]
That's the driver I've been trying. Make fails for me with:

> make -C /lib/modules/4.1.19+/build M=/home/pi/pancho_brain/driver3
> make[1]: *** /lib/modules/4.1.19+/build: No such file or directory.  Stop.
> Makefile:9: recipe for target 'all' failed
> make: *** [all] Error 2

OS deets:

> Linux pancho 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux

Any idea how to fix?

**Comment by spmp** [comment]
You need the headers package for your kernel I suspect. If problem
persists, start an issue over on that github repo
When headers are install you should see /lib/modules/4.1.19+/build as a
link to something in /usr/src/

**Comment by wrybread** [comment]
Very cool! The MT50 seems to be working fine simultaneously with my script when using an ethernet splitter. Don't know if it matters but I'm using this one:

https://www.amazon.com/gp/product/B01K74FGXY

My script gets an occasional error, but easily handled. And the red "warning" light on the MT50 has lit up a couple of times, but it appears to be happily reading the status from the charge controller usually. I'll know more after a few days of testing.

My Python test script is attached in case anyone wants to try it. Change the file extension to .py.

On a sidenote, has anyone figured out how to make it so the backlight on the MT50 stays on longer? I went into "Device Parameters" and changed it to 5 minutes but no matter what setting I use it stays on for only 20 seconds.



[test_script.txt](https://github.com/toggio/PhpEpsolarTracer/files/1206821/test_script.txt)

**Comment by wrybread** [comment]
Sorry, after a day of testing it looks like the splitter causes problems. The MT50 board locks up, or only my script or the MT50 gets data. Currently I don't understand why exactly, since the stripped down test script I posted still works fine with the MT50 connected simultaneously, currently my theory is that my regular script reads multiple registers while my test script only reads one.

But I wanted to correct this in case someone makes plans based on my above post.

Will try to post another update after I fully wrap my head around the issues.

**Comment by spmp** [comment]
I believe the reason for this is clear, and I have been surprised that
anyone of us have had the success we have had so far:

From my understanding the <insert name of bus here> bus is a master ->
slaves topology. The MT50 and the PhpEpSolarTracer/RS485Adaptor are acting
as masters, sending commands to the solar controller slave which in return
responds with data.
Thus with two master's sending commands out of sync they will undoubtedly
clash. If the MT50 is using its polling frequency to calculate energy per
day or SOC then this too will be corrupted as it will be receiving more
data than expected.

The solution seems to be, in the case of having an MT50 on the line with a
splitter, to have PhpEPSolarTracer simply sniff the wire, and process
completed packets from the solar controller as they arrive.

Can this be done? It would be great to have a passive, or sniffing mode 8)

Cheers

**Comment by wrybread** [comment]
> Thus with two master's sending commands out of sync they will undoubtedly
clash.

True, but my test script clashes very infrequently, maybe 1 in 100 queries. 

A possible workaround might be to close the connection (the client) between queries, and add a pause?

>  If the MT50 is using its polling frequency to calculate energy per
day or SOC then this too will be corrupted as it will be receiving more
data than expected.

The MT50 doesn't calculate either of these things, the charge controller does, the MT50 is simply reporting the value it receives after querying it. You can see all the values that the charge controller is storing here fyi:

http://www.solar-elektro.cz/data/dokumenty/1733_modbus_protocol.pdf

**Comment by runsnbunsn** [comment]
Sorry to reopen this, but your findings about connecting an mt50 plus the USB/RS485 Adapter made me curious. Did it work out for you on the long run without a lot of connection issues?
Trying to decide if I should buy an MT50 over a DiY solution with an LCD and the Bananapi the Tracer is connected to now.

**Comment by spmp** [comment]
It did not work for me.
 I may have been doing it wrong (?)

**Comment by runsnbunsn** [comment]
sorry to hear that, but thanks for the answer. looks like DiY it is...

**Comment by wrybread** [comment]
It didn't work for me. And connecting to the tracer directly was
unreliable, I suspect because of grounding issues. Every time I would think
it's finally fixed it would stop responding for hours or days. I finally
gave up when someone gave me a Morningstar mppt60 controller. It's a shame
because I love the tracer but its modus interface seems to be very
sensitive to grounding issues. Or maybe I was just doing something wrong.
